Repository Sinnabro/Sinnabro_Backend, pull requests merged in 2022-10, with the labels that each got.

#2 (#1) Create files project setting
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/controllers/.gitkeep
  src/models/index.js
  src/routes/index.js
Labels: 프로젝트 세팅

#4 (#3) Create signup
  src/controllers/.gitkeep
  src/controllers/user.js
  src/models/index.js
  src/models/user.js
  src/routes/index.js
  src/routes/user.js
Labels: 기능 추가

#6 (#5) Create name checking
  .gitignore
  src/app.js
  src/controllers/user.js
  src/models/index.js
  src/models/user.js
  src/routes/user.js
Labels: 기능 추가

#8 (#7) Create node login api
  src/app.js
  src/controllers/user.js
  src/middleware/token.js
  src/routes/user.js
Labels: 기능 추가

#10 (#9) Create delete user
  src/controllers/user.js
  src/middleware/token.js
  src/models/user.js
  src/routes/user.js
Labels: 기능 추가

#12 (#11) Create node update password api
  src/controllers/user.js
  src/routes/user.js
Labels: 기능 추가

#15 Todo 작성 기능추가
  src/controllers/todo.js
  src/models/index.js
  src/models/todo.js
  src/routes/index.js
  src/routes/todo.js
Labels: 기능 추가

#17 (#16) Update create todo
  src/controllers/todo.js
  src/controllers/user.js
  src/models/index.js
  src/models/todo.js
  src/routes/todo.js
Labels: 기능 수정

#20 (#19) Create comment
  src/controllers/comment.js
  src/models/comment.js
  src/models/index.js
  src/routes/comment.js
  src/routes/index.js
Labels: 기능 추가

#22 (#21) Create node delete one comment api
  src/controllers/comment.js
  src/routes/comment.js
Labels: 기능 추가
